spring.application.name=blog-backend

spring.data.mongodb.uri=mongodb+srv://bloguser:SbV2yDZn8v1vvTW0@blog-platform-cluster.bdgo5f5.mongodb.net/blogdb?retryWrites=true&w=majority
spring.data.mongodb.database=blogdb

server.address = 0.0.0.0
server.port = 8080
